### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by UltCombo** [es6rocks/harmonic-theme-jsrocks#10]
TESTEMONIALS -> TESTIMONIALS
"Search anything?" - the phrase doesn't make much (or any) sense. Perhaps "Looking for something?" or just "Search" would be good.

cc @robsongajunior @jaydson

**Comment by jaydson** [comment]
Please take a look @robsongajunior

**Comment by robsongajunior** [comment]
of course, i will fix this

**Comment by robsongajunior** [comment]
#fixed

https://github.com/es6rocks/harmonic-theme-jsrocks/commit/8a46015ab056d99896161fd565e2c7112eda73cb

**Comment by UltCombo** [comment]
@robsongajunior "Search anything?" hasn't been fixed. I guess we can leave just "Search".

**Comment by robsongajunior** [comment]
Sorry, had not understood!

Status: updated

**Comment by UltCombo** [comment]
Nice! :+1:

**Comment by UltCombo** [comment]
@robsongajunior by the way, do you have hangouts/gtalk?
