### ISSUE TITLE
page template is erroring

### ISSUE THREAD

**Issue by UltCombo** [es6rocks/harmonic-theme-jsrocks#11]
Note that this is low priority for now as we do not have pages yet.

If you create a new page (`harmonic new_page "hey"`), trying to build the site will throw an error because the `partials/navigation.html` tries to include `partials/components/avatar.html` which doesn't exist. Also, the generated HTML does not look ok  -- the page title appears twice, and so does `</body></html>`, this is most likely an issue with the includes structure.

IIRC @jaydson is making a video gallery so it'd be nice to have pages working.
cc @robsongajunior

**Comment by robsongajunior** [comment]
At moment, template page can be like article?
This is a temporarily problem solution, of course with include correction!

cc @jaydson @UltCombo

**Comment by UltCombo** [comment]
Don't worry too much about this, I've just filed the issue so it isn't lost in the limbo.
The Harmonic site, JS Rocks and all the other issues have higher priority. `:D`

**Comment by robsongajunior** [comment]
@UltCombo  @jaydson 
Can you verify, please?

https://github.com/es6rocks/harmonic-theme-jsrocks/commit/8a46015ab056d99896161fd565e2c7112eda73cb

**Comment by UltCombo** [comment]
@robsongajunior nice work. ^^
