### ISSUE TITLE
Remove/fix dead code

### ISSUE THREAD

**Issue by UltCombo** [es6rocks/harmonic-theme-jsrocks#26]
There are quite a few `body[data-page-type="..."]` CSS selectors which are not being used, please check whether they should be removed or applied to a different selector.
cc @robsongajunior @italowaxman

**Comment by robsongajunior** [comment]
I will take a look

**Comment by robsongajunior** [comment]
finished?

**Comment by UltCombo** [comment]
@robsongajunior nop. Can you take at this when you have time? This is low priority though.

**Comment by robsongajunior** [comment]
I'm thinking here, we can close this.

**Comment by UltCombo** [comment]
@robsongajunior Good call, it looks like this has already been fixed.
