### ISSUE TITLE
CN categories link

### ISSUE THREAD

**Issue by robsongajunior** [es6rocks/harmonic-theme-jsrocks#27]
Categories link isn't supported in CN language. I'm looking for this.

**Comment by UltCombo** [comment]
Categories links are actually bugged in all non-English languages -- they're linking to the English category.

**Comment by UltCombo** [comment]
Wait, it is just the CN categories that are linking to the English categories. This is weird, the pt-br categories work fine and they use the same template.

**Comment by robsongajunior** [comment]
it's easy to do a correction, i'm just checking if is pt-br else use default lang. One more case on switch case in the main.js archive

**Comment by robsongajunior** [comment]
i will take a look

**Comment by UltCombo** [comment]
@robsongajunior it would be nice if you could use a if/else testing if `lang == config.i18n.default` as in https://github.com/JSRocksHQ/harmonic-theme-jsrocks/blob/49f22ef25bfc5a2342fde505850d98502abb275e/partials/navigation.html#L5
This way you don't need `case` nor extra `if`s.

**Comment by robsongajunior** [comment]
Flags ok, but categories not yet. It's so strange final result oO
Me and @jaydson we will take a look tomorrow at morning.

status: not fixed yet

**Comment by robsongajunior** [comment]
fixed.

https://github.com/robsongajunior/harmonic-theme-jsrocks/commit/878e63401ad9d3719275164259afff4b8744cd89

**Comment by robsongajunior** [comment]
closed issue?

cc/ @UltCombo @jaydson

**Comment by UltCombo** [comment]
Yeah, nice work @robsongajunior :smile:
