### ISSUE TITLE
CN lang.

### ISSUE THREAD

**Issue by robsongajunior** [es6rocks/harmonic-theme-jsrocks#3]
Today, chinese language isn't supported.

**Comment by UltCombo** [comment]
The old (current) theme had (has) the template's text hardcoded in English, is it the same with the new template?

**Comment by robsongajunior** [comment]
hmmmm, great question.
I just thought cases how link categories.

We need talk about this.

**Comment by UltCombo** [comment]
The categories can stay in English in the Chinese site for the time being, I guess.

**Comment by UltCombo** [comment]
What I mean is, the Chinese posts currently have some categories in English and some in Chinese, we could put all categories in English until Harmonic supports categories written in Chinese.

**Comment by UltCombo** [comment]
The Chinese version looks ok. http://jsrocks.org/cn/
Let's center the template i18n discussion here: https://github.com/es6rocks/es6rocks.github.io/issues/60
