### ISSUE TITLE
The "posts" menu directs to the home page

### ISSUE THREAD

**Issue by ftonato** [es6rocks/harmonic-theme-jsrocks#34]
Is it supposed to work this way?

/cc @felipenmoura

**Comment by UltCombo** [comment]
In a non-English page (e.g. http://jsrocks.org/pt-br/), the "posts" nav and the logo link to the home page (English). Is this what you mean?

If so, I believe it should link to the current language's home page.
Both logo and "posts" menu will link to the same page, as the home page is actually the only posts listing (besides category-specific post listings).

**Comment by UltCombo** [comment]
cc @robsongajunior @jaydson

**Comment by robsongajunior** [comment]
hmmmmm, You're right, I will check this.

**Comment by ftonato** [comment]
@UltCombo Yeah!

**Comment by robsongajunior** [comment]
fixed https://github.com/JSRocksHQ/harmonic-theme-jsrocks/pull/36

**Comment by robsongajunior** [comment]
menu not fixed, tomorrow i will check this

**Comment by ftonato** [comment]
I'm closing outdated issues and pull-requests that are no longer relevant given how much time has passed since they were opened.
