### ISSUE TITLE
The JS logo on the footer has no destination

### ISSUE THREAD

**Issue by ftonato** [es6rocks/harmonic-theme-jsrocks#35]
We could use background-image instead of an img tag, also.

/cc @felipenmoura

**Comment by robsongajunior** [comment]
thanks, I will check..

**Comment by robsongajunior** [comment]
fixed https://github.com/JSRocksHQ/harmonic-theme-jsrocks/pull/36

**Comment by ftonato** [comment]
@robsongajunior you added the url, but the target value was wrong `target="_blan"`

**Comment by robsongajunior** [comment]
true history, thanks...

**Comment by robsongajunior** [comment]
> The JS logo on the footer has no destination

**fixed**
