### ISSUE TITLE
Testimonials: broken profile images

### ISSUE THREAD

**Issue by UltCombo** [es6rocks/harmonic-theme-jsrocks#39]
![](https://www.evernote.com/l/AhYF7lJIsN5Kiod2Xl2IoABnYQUT4d1rdAQB/image.png)

Perhaps it would be better to host these images on the site instead of hotlinking to 3rd-party services.

cc @robsongajunior @jaydson

**Comment by mateusortiz** [comment]
created testimonials directory with the images, and removed the 3rd-party services.

**Comment by UltCombo** [comment]
Deployed it now, thanks!

**Comment by mateusortiz** [comment]
:wink:
