### ISSUE TITLE
Wrong cards summary

### ISSUE THREAD

**Issue by jaydson** [es6rocks/harmonic-theme-jsrocks#7]
All cards are assuming a single summary:

> Among so many great new features in ES6, Arrow Functions(or Fat Arrow Functions) is one that desirves attention! It is not just awesome, it's also great to work with scopes, shortcuts some tecniques ...

![screenshot from 2015-04-09 11 14 09](https://cloud.githubusercontent.com/assets/72206/7068573/acf012a0-dea9-11e4-94b4-8deddc927fb5.png)

//cc @robsongajunior

**Comment by robsongajunior** [comment]
Sorry,
all cards was written a fixed summary.

This correction can be found at
[*] update - All cards are assuming a single summary bugfix

PullRequest https://github.com/es6rocks/harmonic-theme-jsrocks/pull/6

**Comment by jaydson** [comment]
fixed by #6
