### ISSUE TITLE
Having issues to compile with the latest Stylus

### ISSUE THREAD

**Issue by UltCombo** [es6rocks/harmonic-theme-jsrocks#9]
Getting error:

```
ParseError: C:/repos/es6rocks.github.io/node_modules/harmonic-theme-jsrocks/resources/_stylus/style/bootstrap.styl:3477:
71
   3473|   text-decoration: none;
   3474|   cursor: not-allowed;
   3475|   background-color: transparent;
   3476|   background-image: none;
   3477|   filter: progid:DXImageTransform.Microsoft.gradient(enabled = false);
-------------------------------------------------------------------------------^
   3478| }
   3479| .open > .dropdown-menu {
   3480|   display: block;

expected "indent", got ";"
```

Looks like the latest Stylus (0.50.0) doesn't like the bootstrap.styl.

**Comment by UltCombo** [comment]
I just fixed a bug on my local Harmonic which was silently ignoring CSS preprocessor errors, so that might be why no one has run into this issue yet.

**Comment by UltCombo** [comment]
Confirmed. This is a bug with our `.styl` files which was going unnoticed until now due a bug in Harmonic.

**Comment by UltCombo** [comment]
@robsongajunior if you are not using those `.styl` files, please remove them from the project otherwise we won't be able to build JS Rocks with the latest Harmonic release.

**Comment by robsongajunior** [comment]
Today, JSRocks's style is pure css, I really want do a transformation to .styl preprocessor. So, at moment, I will remove .styl archives to fix those errors.

**Comment by UltCombo** [comment]
Harmonic's master branch now accepts setting `"preprocessor": false` in the `harmonic.json` or theme's `config.json` to disable preprocessing, so you no longer have to remove those files.

I've [temporarily disabled preprocessing in this theme](https://github.com/es6rocks/harmonic-theme-jsrocks/blob/9b46578fd80006b232ef7e608e0ba23f8fdfa9a0/config.json#L2), until you decide to start using Stylus and fix those `.styl` files.
